### ISSUE TITLE
宝钻药剂生效期间暴击率提高导入后是乱码

### ISSUE THREAD

**Issue by Dzs-HF** [cn-poe-community/poexport#1]
宝钻药剂生效期间暴击率提高导入后是乱码
![QQ截图20230124134026](https://user-images.githubusercontent.com/105147165/214220195-821b1314-5e95-4eb8-9c70-f553f34e83aa.jpg)

**Comment by me1ting** [comment]
请问中文词缀是啥

**Comment by me1ting** [comment]
已修复 [c7b3de9](https://github.com/me1ting/poe-cn-export/commit/c7b3de972cb8fd8561f3e4f0c5c99c846642347a)
