### ISSUE TITLE
不好用了，提取信息会刷新session，无法提取成功

### ISSUE THREAD

**Issue by j4tmr** [cn-poe-community/poexport#4]

**Comment by me1ting** [comment]
请使用[插件版本](https://github.com/cn-poe-community/poexport-extension)。

由于国服更新了http会话管理机制，不再支持直接使用poesessid获取API数据，需要使用多个cookies数据，这复杂性已经超过了浏览器插件，因此我认为客户端没有继续支持的必要。

**Comment by j4tmr** [comment]
@me1ting 嗯嗯，前面已经试过插件，确实好用！
